import type { Metadata } from 'next';

export const siteConfig = {
  name: 'Shivanksha Travels',
  description:
    'Discover unforgettable travel experiences with Shivanksha Travels. We offer customized tour packages, destination guides, and expert travel planning services.',
  url: 'https://shivankshatravels.in',
  ogImage: 'https://shivankshatravels.in/og-image.jpg',
  links: {
    facebook: 'https://facebook.com/shivankshatravels',
    instagram: 'https://instagram.com/shivankshatravels',
    twitter: 'https://twitter.com/shivankshatravels',
  },
};

export const defaultMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    'travel',
    'tours',
    'travel packages',
    'vacation',
    'holiday',
    'destinations',
    'travel agency',
    'tour operator',
    'Uttarakhand tourism',
    'Chardham Yatra',
    'spiritual travel',
    'adventure tours india',
    'Dev Bhoomi',
    'Rishikesh rafting',
    'Kedarnath trip',
    'Badrinath tour',
    'Gangotri dham',
    'Yamunotri temple',
    'Haridwar ganga aarti',
    'Mussoorie hill station',
    'Nainital lake tour',
    'Auli skiing',
    'Jim Corbett safari',
    'Valley of Flowers trek',
    'Hemkund Sahib yatra',
    'Tungnath trek',
    'Chopta camping',
    'Dehradun travel guide',
    'Rishikesh yoga retreat',
    'best travel agency in Uttarakhand',
    'Uttarakhand tour packages',
    'family trip to uttarakhand',
    'honeymoon packages uttarakhand',
    'solo travel himalayas',
    'group tour packages india',
    'religious tourism india',
    'himalayan trekking',
    'river rafting rishikesh',
    'bungee jumping rishikesh',
    'wildlife safari india',
    'luxury resorts uttarakhand',
    'budget travel uttarakhand',
    'char dham yatra package 2025',
    'helipad services kedarnath',
    'badrinath hotel booking',
    'guptkashi hotels',
    'sonprayag stay',
    'gaurikund trek',
    'panch kedar yatra',
    'panch badri tour',
    'adi kailash yatra',
    'om parvat tour',
    'pithoragarh tourism',
    'munsiari hill station',
    'binsar wildlife sanctuary',
    'kausani sightseeing',
    'ranikhet tourism',
    'mukteshwar homestays',
    'kanatal camping',
    'dhanaulti eco park',
    'tehri dam water sports',
    'new tehri tourism',
    'landsdowne army cantonment',
    'chakrata hill station',
    'best time to visit uttarakhand',
    'summer vacation places in india',
    'winter snow places in india',
  ],
  authors: [{ name: 'Shivanksha Travels' }],
  creator: 'Shivanksha Travels',
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: siteConfig.name,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.name,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: '@shivankshatravels',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon-16x16.png',
    apple: '/apple-touch-icon.png',
  },
  manifest: '/site.webmanifest',
};
